databases:
  - name: 65-shu_DB
    databaseName: 65-shu_db
    user: 65-shu
    region: singapore

services:
  - type: web
    name: 65-shu
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: 65-shu_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

